"""Build the TATS playable graph from the public Sejong node-link data.

`unity/.../eojin_map.json` is the *visual* map (884 road polylines). This script
builds the *simulatable* graph: signalized intersections, their legs, directed
links, turn movements, pedestrian crossings, the vehicle conflict matrix and
default signal plans.

The national node-link standard splits one intersection into one node per leg
(성금교차로 = 4130092501~504). Those member nodes give the real leg geometry, so
legs are read from them rather than guessed. Legs are indexed by clockwise order,
NOT snapped to compass N/E/S/W — the real crossings here meet at ~48°, and
snapping collapses two distinct legs into one sector.

Geometry and adjacency come from public data. Turn movements, conflicts,
crossings, signal timing and demand are generated by rule and are synthetic.

Deterministic: same input files -> byte-identical output.
"""
from __future__ import annotations

import collections
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NODE_SRC = ROOT / "data/public/2026-07-29/sejong_nodelink_node.geojson"
LINK_SRC = ROOT / "data/public/2026-07-29/sejong_nodelink_link.geojson"
OUTPUT = ROOT / "backend/content/map_eojin_playable.json"

MAP_VERSION = "tats-playable-v1"
ORIGIN = (127.2785, 36.5040)
BBOX = (127.2550, 36.4950, 127.3020, 36.5130)

# docs/20 4.2절 "3개 시작점".
START_INTERSECTIONS = ("성금교차로", "청사교차로", "어진교차로")
INTERSECTION_SUFFIXES = ("교차로", "사거리", "삼거리")

# 도로를 따라가며 다음 신호교차로를 찾을 때 허용할 최대 형상점 수.
MAX_CORRIDOR_HOPS = 40
# 접근로 대기공간(대) = 길이 × 차로수 ÷ 차두간격
HEADWAY_M = 7.0
# 정지선 포화교통류율(대/초/차로)
SATURATION_VEH_PER_SEC_PER_LANE = 0.5
COMPASS = ("북", "북동", "동", "남동", "남", "남서", "서", "북서")


def _meters(lon: float, lat: float) -> tuple[float, float]:
    return (
        round((lon - ORIGIN[0]) * 111_320.0 * math.cos(math.radians(ORIGIN[1])), 2),
        round((lat - ORIGIN[1]) * 110_540.0, 2),
    )


def _inside(coord: list[float]) -> bool:
    return BBOX[0] <= coord[0] <= BBOX[2] and BBOX[1] <= coord[1] <= BBOX[3]


def _bearing(origin: tuple[float, float], target: tuple[float, float]) -> float:
    return math.degrees(math.atan2(target[0] - origin[0], target[1] - origin[1])) % 360.0


def _compass(bearing: float) -> str:
    return COMPASS[int(((bearing + 22.5) % 360.0) // 45.0)]


def _entry_slot(leg_index: int, leg_count: int) -> int:
    """우측통행 교차로를 2n분할한 원 위의 진입 지점.

    시계방향으로 leg i의 유출점이 2i, 유입점이 2i-1에 온다.
    남행 차량은 북쪽 도로의 서쪽 절반으로 들어오므로 유입점이 유출점보다 앞선다.
    """
    return (2 * leg_index - 1) % (2 * leg_count)


def _exit_slot(leg_index: int, leg_count: int) -> int:
    return (2 * leg_index) % (2 * leg_count)


def _chords_cross(a: tuple[int, int], b: tuple[int, int], size: int) -> bool:
    """원 위의 두 현이 내부에서 교차하는가.

    a의 끝점이 만드는 호 안에 b의 끝점이 정확히 하나만 있으면 교차한다.
    이 판정 하나가 마주보는 좌회전 상충과 직진 횡단 상충을 모두 잡아낸다.
    """
    (a1, a2), (b1, b2) = a, b
    if len({a1, a2, b1, b2}) < 4:
        return False
    span = {(a1 + step) % size for step in range(1, (a2 - a1) % size)}
    return (b1 in span) != (b2 in span)


def _turn_of(from_index: int, to_index: int, leg_count: int) -> str:
    """시계방향 leg 순서에서의 회전 종류. 우측통행 기준."""
    step = (to_index - from_index) % leg_count
    if step == 0:
        return "uturn"
    if leg_count == 2:
        return "through"
    half = leg_count / 2
    if abs(step - half) < 0.5:
        return "through"
    return "left" if step < half else "right"


def load_network() -> tuple[dict, dict, dict, dict]:
    nodes = json.loads(NODE_SRC.read_text(encoding="utf-8"))
    links = json.loads(LINK_SRC.read_text(encoding="utf-8"))

    position: dict[str, tuple[float, float]] = {}
    cluster_of: dict[str, str] = {}
    members: dict[str, list[str]] = collections.defaultdict(list)
    for feature in nodes["features"]:
        props = feature["properties"]
        coord = feature["geometry"]["coordinates"]
        if not _inside(coord):
            continue
        node_id = str(props["NODE_ID"])
        position[node_id] = _meters(coord[0], coord[1])
        name = (props.get("NODE_NAME") or "").strip()
        if name and str(props.get("NODE_TYPE")) == "101":
            cluster_of[node_id] = name
            members[name].append(node_id)

    outgoing: dict[str, list[dict]] = collections.defaultdict(list)
    for feature in links["features"]:
        props = feature["properties"]
        head, tail = str(props.get("F_NODE")), str(props.get("T_NODE"))
        if head not in position or tail not in position:
            continue
        outgoing[head].append(
            {
                "to": tail,
                "roadId": str(props.get("LINK_ID")),
                "lengthM": float(props.get("LENGTH") or 0.0),
                "lanes": int(props.get("LANES") or 1),
                "maxSpeedKph": int(props.get("MAX_SPD") or 0),
            }
        )
    return position, cluster_of, members, outgoing


def trace_corridor(
    start_node: str, origin_name: str, cluster_of: dict, outgoing: dict, signalized: set
) -> dict:
    """한 leg에서 도로를 따라가 가장 가까운 다른 신호교차로를 찾는다.

    중간의 무명 형상점들은 통과 지점일 뿐이므로 하나의 링크로 합친다.
    출발 교차로의 다른 멤버 노드(내부 연결)는 지나가지 않는다.

    분기점에서 굵은 길을 탐욕적으로 따라가면 A->B는 찾고 B->A는 못 찾는
    비대칭이 생긴다. 거리 기준 최단경로로 찾아야 양방향이 일치한다.
    """
    best: tuple[float, str, list[str], int, int] | None = None
    dist = {start_node: 0.0}
    frontier: list[tuple[float, str, list[str], int, int]] = [(0.0, start_node, [], 1, 0)]
    while frontier:
        frontier.sort(key=lambda item: (item[0], item[1]))
        total, current, roads, lanes, speed = frontier.pop(0)
        if len(roads) > MAX_CORRIDOR_HOPS:
            continue
        for edge in sorted(outgoing.get(current, []), key=lambda item: item["roadId"]):
            target = edge["to"]
            if cluster_of.get(target) == origin_name:
                continue
            step = total + edge["lengthM"]
            if step >= dist.get(target, float("inf")):
                continue
            dist[target] = step
            reached = (
                step,
                target,
                roads + [edge["roadId"]],
                max(lanes, edge["lanes"]),
                max(speed, edge["maxSpeedKph"]),
            )
            if cluster_of.get(target) in signalized:
                if best is None or step < best[0]:
                    best = reached
                continue  # 교차로에 닿으면 그 너머로는 가지 않는다
            frontier.append(reached)

    if best is not None:
        total, node, roads, lanes, speed = best
        return {
            "toName": cluster_of[node],
            "lengthM": round(total, 1),
            "lanes": lanes,
            "maxSpeedKph": speed or 50,
            "sourceRoadIds": roads,
        }
    # 다른 교차로에 닿지 않는 leg는 지도 경계다. 차량이 여기로 드나든다.
    reach = max((value for value in dist.values()), default=0.0)
    return {
        "toName": None,
        "lengthM": round(reach, 1) or 200.0,
        "lanes": 2,
        "maxSpeedKph": 50,
        "sourceRoadIds": [],
    }


def _is_real_intersection(ids: list[str], position: dict) -> bool:
    """도로명 클러스터를 걸러낸다.

    `다솜1로교차로`처럼 회랑 전체에 같은 이름이 붙은 클러스터는 멤버가 10개고
    방위가 두 갈래에 몰려 있다. 진짜 신호교차로는 멤버 3~4개가 서로 다른
    방향으로 뻗는다.
    """
    if not 3 <= len(ids) <= 4:
        return False
    cx = sum(position[i][0] for i in ids) / len(ids)
    cy = sum(position[i][1] for i in ids) / len(ids)
    bearings = sorted(_bearing((cx, cy), position[i]) for i in ids)
    gaps = [
        (right - left) % 360.0
        for left, right in zip(bearings, bearings[1:] + [bearings[0] + 360.0])
    ]
    return min(gaps) >= 30.0


def build() -> dict:
    position, cluster_of, members, outgoing = load_network()
    signalized = {
        name
        for name in members
        if name.endswith(INTERSECTION_SUFFIXES)
        and _is_real_intersection(sorted(members[name]), position)
    }
    # 교차로로 인정하지 않은 클러스터는 도로 위 통과 지점으로 되돌린다.
    cluster_of = {
        node_id: name for node_id, name in cluster_of.items() if name in signalized
    }

    # 1) 교차로마다 멤버 노드를 시계방향으로 정렬해 leg로 만든다.
    legs: dict[str, list[dict]] = {}
    centroid: dict[str, tuple[float, float]] = {}
    for name in sorted(signalized):
        ids = sorted(members[name])
        cx = round(sum(position[i][0] for i in ids) / len(ids), 2)
        cy = round(sum(position[i][1] for i in ids) / len(ids), 2)
        centroid[name] = (cx, cy)
        ordered = sorted(ids, key=lambda i: (_bearing((cx, cy), position[i]), i))
        legs[name] = [
            {
                "nodeId": node_id,
                "bearingDeg": round(_bearing((cx, cy), position[node_id]), 1),
            }
            for node_id in ordered
        ]

    # 2) leg마다 도로를 따라가 상대 교차로를 찾는다.
    for name in sorted(signalized):
        for index, leg in enumerate(legs[name]):
            leg["corridor"] = trace_corridor(
                leg["nodeId"], name, cluster_of, outgoing, signalized
            )
            leg["index"] = index

    # 3) 시작 교차로에서 도달 가능한 것만 남긴다.
    adjacency = collections.defaultdict(set)
    for name in signalized:
        for leg in legs[name]:
            target = (leg["corridor"] or {}).get("toName")
            if target:
                adjacency[name].add(target)
                adjacency[target].add(name)
    reachable, queue = set(START_INTERSECTIONS), collections.deque(START_INTERSECTIONS)
    while queue:
        for neighbour in sorted(adjacency[queue.popleft()]):
            if neighbour not in reachable:
                reachable.add(neighbour)
                queue.append(neighbour)
    kept = sorted(name for name in signalized if name in reachable)
    slug = {name: f"ix_{index:02d}" for index, name in enumerate(kept)}

    links, boundaries = _build_links(kept, legs, slug)
    link_by_id = {link["id"]: link for link in links}
    intersections = [
        _build_intersection(name, slug, centroid, members, legs, link_by_id, boundaries)
        for name in kept
    ]
    buildings = _build_buildings(links)
    start_ids = [slug[name] for name in START_INTERSECTIONS if name in slug]
    # 플레이어는 시작점 하나를 고르고 거기서부터 넓혀 간다.
    # 세 곳을 한꺼번에 열면 확장할 것이 남지 않는다.
    open_links = {
        start: sorted(
            link["id"]
            for link in links
            if start in (link["fromIntersectionId"], link["toIntersectionId"])
        )
        for start in start_ids
    }

    return {
        "schemaVersion": 1,
        "mapVersion": MAP_VERSION,
        "realityLevel": {
            "geometry": "public_nodelink_2026_07_16",
            "adjacency": "public_nodelink_2026_07_16",
            "turnMovements": "synthetic_generated",
            "signalTiming": "synthetic_generated",
            "demand": "synthetic_generated",
        },
        "note": (
            "도로 형상과 연결 관계만 공개 표준노드링크에서 왔다. "
            "회전 이동·신호 현시·교통량·건물 수요는 게임용 합성값이며 "
            "실제 세종 신호 운영을 나타내지 않는다."
        ),
        "origin": {"longitude": ORIGIN[0], "latitude": ORIGIN[1]},
        "bounds": {"west": BBOX[0], "south": BBOX[1], "east": BBOX[2], "north": BBOX[3]},
        "startIntersectionIds": start_ids,
        "initiallyOpenLinkIdsByStart": open_links,
        "intersections": intersections,
        "links": links,
        "buildings": buildings,
    }


def _build_links(kept: list, legs: dict, slug: dict) -> tuple[list, dict]:
    """교차로 사이 링크와, 지도 경계로 나가는 유입원·유출구를 만든다."""
    links: list[dict] = []
    seen: set[str] = set()
    boundaries: dict[str, str] = {}

    def add(link_id: str, tail: str, head: str, data: dict, kind: str) -> None:
        if link_id in seen:
            return
        seen.add(link_id)
        links.append(
            {
                "id": link_id,
                "kind": kind,
                "fromIntersectionId": tail,
                "toIntersectionId": head,
                "lengthM": data["lengthM"],
                "lanes": data["lanes"],
                "maxSpeedKph": data["maxSpeedKph"],
                "storageVeh": max(4, int(data["lengthM"] * data["lanes"] / HEADWAY_M)),
                "saturationVehPerSec": round(
                    SATURATION_VEH_PER_SEC_PER_LANE * data["lanes"], 3
                ),
                "sourceRoadIds": sorted(set(data["sourceRoadIds"])),
            }
        )

    for name in kept:
        for leg in legs[name]:
            corridor = leg.get("corridor")
            if not corridor:
                continue
            target = corridor["toName"]
            if target in slug:
                add(f"lk_{slug[name]}_{slug[target]}", slug[name], slug[target], corridor, "street")
                add(f"lk_{slug[target]}_{slug[name]}", slug[target], slug[name], corridor, "street")
            else:
                # 지도 밖으로 나가는 leg. 차량이 여기서 들어오고 여기로 빠져나간다.
                gate = f"gate_{slug[name]}_{leg['index']}"
                boundaries[f"{slug[name]}:{leg['index']}"] = gate
                add(f"lk_{gate}_{slug[name]}", gate, slug[name], corridor, "inbound_gate")
                add(f"lk_{slug[name]}_{gate}", slug[name], gate, corridor, "outbound_gate")
    links.sort(key=lambda item: item["id"])
    return links, boundaries


def _build_intersection(
    name: str,
    slug: dict,
    centroid: dict,
    members: dict,
    legs: dict,
    link_by_id: dict,
    boundaries: dict,
) -> dict:
    ident = slug[name]
    own_legs = legs[name]
    count = len(own_legs)

    approaches, movements = [], []
    for leg in own_legs:
        target = (leg["corridor"] or {}).get("toName")
        if target in slug:
            inbound = f"lk_{slug[target]}_{ident}"
        else:
            gate = boundaries.get(f"{ident}:{leg['index']}")
            inbound = f"lk_{gate}_{ident}" if gate else None
        if inbound not in link_by_id:
            continue
        approach_id = f"{ident}:L{leg['index']}"
        approaches.append(
            {
                "id": approach_id,
                "legIndex": leg["index"],
                "bearingDeg": leg["bearingDeg"],
                "compassLabel": _compass(leg["bearingDeg"]),
                "fromLinkId": inbound,
                "lanes": link_by_id[inbound]["lanes"],
                "saturationVehPerSec": link_by_id[inbound]["saturationVehPerSec"],
                "sourceNodeId": leg["nodeId"],
            }
        )

    live = {approach["legIndex"] for approach in approaches}
    for approach in approaches:
        source = approach["legIndex"]
        for leg in own_legs:
            destination = leg["index"]
            if destination == source or destination not in live:
                continue
            target = (leg["corridor"] or {}).get("toName")
            if target in slug:
                outbound = f"lk_{ident}_{slug[target]}"
            else:
                gate = boundaries.get(f"{ident}:{destination}")
                outbound = f"lk_{ident}_{gate}" if gate else None
            if outbound not in link_by_id:
                continue
            movements.append(
                {
                    "id": f"{approach['id']}>L{destination}",
                    "approachId": approach["id"],
                    "fromLegIndex": source,
                    "toLegIndex": destination,
                    "turn": _turn_of(source, destination, count),
                    "toLinkId": outbound,
                    "_chord": (
                        _entry_slot(source, count),
                        _exit_slot(destination, count),
                    ),
                }
            )

    conflicts = sorted(
        [left["id"], right["id"]]
        for index, left in enumerate(movements)
        for right in movements[index + 1 :]
        if left["approachId"] != right["approachId"]
        and _chords_cross(left["_chord"], right["_chord"], 2 * count)
    )

    crossings = []
    for approach in approaches:
        width = 3.25 * max(1, approach["lanes"]) * 2
        crossings.append(
            {
                "id": f"{ident}#L{approach['legIndex']}",
                "legIndex": approach["legIndex"],
                "widthM": round(width, 1),
                # 보행속도 1.0 m/s + 반응 5초 (합성값)
                "walkSec": int(round(width)) + 5,
                "conflictingMovementIds": sorted(
                    movement["id"]
                    for movement in movements
                    if approach["legIndex"]
                    in (movement["fromLegIndex"], movement["toLegIndex"])
                ),
            }
        )

    for movement in movements:
        movement.pop("_chord")

    return {
        "id": ident,
        "name": name,
        "position": list(centroid[name]),
        "sourceNodeIds": sorted(members[name]),
        "approaches": approaches,
        "movements": movements,
        "crossings": crossings,
        "conflictingMovementPairs": conflicts,
        "defaultPlan": _default_plan(ident, approaches, movements, crossings, conflicts),
    }


def _default_plan(
    ident: str, approaches: list, movements: list, crossings: list, conflicts: list
) -> dict:
    """상충이 없는 보수적 기본 계획.

    마주보는 leg를 한 축으로 묶어 직진·우회전을 먼저 주고 좌회전을 분리한다.
    안전하지만 느리다 — 플레이어가 개선할 여지를 남기는 것이 의도다.
    상충쌍이 남으면 그 단계를 접근로 단위로 더 쪼갠다.
    """
    banned = {tuple(pair) for pair in conflicts}
    count = len(approaches)
    indices = [approach["legIndex"] for approach in approaches]
    axes: list[tuple[int, ...]] = []
    used: set[int] = set()
    for index in indices:
        if index in used:
            continue
        opposite = next(
            (other for other in indices if other != index and (other - index) % count * 2 == count),
            None,
        )
        axes.append((index, opposite) if opposite is not None else (index,))
        used.update(axes[-1])

    def clean(group: list[str]) -> list[list[str]]:
        """상충쌍이 있으면 접근로별로 쪼갠다."""
        pairs = {(a, b) for a in group for b in group if (a, b) in banned}
        if not pairs:
            return [sorted(group)] if group else []
        by_approach: dict[str, list[str]] = collections.defaultdict(list)
        for movement_id in group:
            by_approach[movement_id.split(">")[0]].append(movement_id)
        return [sorted(v) for _, v in sorted(by_approach.items())]

    stages, order = [], 0
    for axis in axes:
        for turns, label in ((("through", "right"), "직진·우회전"), (("left", "uturn"), "좌회전")):
            group = [
                movement["id"]
                for movement in movements
                if movement["fromLegIndex"] in axis and movement["turn"] in turns
            ]
            for chunk in clean(group):
                order += 1
                # 이 단계의 차량과 상충하지 않는 횡단에만 보행 신호를 준다.
                blocked = {
                    crossing["id"]
                    for crossing in crossings
                    if set(crossing["conflictingMovementIds"]) & set(chunk)
                }
                stages.append(
                    {
                        "stageId": f"{ident}/s{order}",
                        "order": order,
                        "durationSec": 30 if "through" in turns else 15,
                        "allowedVehicleMovements": chunk,
                        "allowedPedestrianCrossings": sorted(
                            crossing["id"] for crossing in crossings if crossing["id"] not in blocked
                        ),
                        "priorityTarget": "None",
                        "label": f"L{'·'.join(str(i) for i in axis)} {label}",
                    }
                )
    return {
        "planId": f"{ident}/default",
        "intersectionId": ident,
        "stages": stages,
        "yellowSec": 3,
        "allRedSec": 2,
        "offsetSec": 0,
    }


def _build_buildings(links: list) -> list:
    """링크마다 수요 발생원을 붙인다. 길고 넓은 도로일수록 많다."""
    types = (("office", 120, 40), ("residential", 60, 90), ("commercial", 90, 110))
    buildings = []
    for link in links:
        if link["kind"] != "street":
            continue
        if link["fromIntersectionId"] > link["toIntersectionId"]:
            continue  # 양방향 중 한 쪽에만 붙인다
        for index in range(1 + min(2, int(link["lengthM"] // 400))):
            kind, vehicles, pedestrians = types[(len(buildings) + index) % len(types)]
            buildings.append(
                {
                    "id": f"bd_{link['id']}_{index}",
                    "buildingType": kind,
                    "level": 1,
                    "linkId": link["id"],
                    "positionRatio": round((index + 1) / (2 + min(2, int(link["lengthM"] // 400))), 3),
                    "baseVehiclePerCityHour": vehicles + 10 * (index % 3),
                    "basePedestrianPerCityHour": pedestrians + 10 * (index % 2),
                    "currentVisualId": f"{kind}_lv1",
                }
            )
    return buildings


def main() -> None:
    payload = build()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(
        (json.dumps(payload, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    )
    gates = sum(1 for link in payload["links"] if link["kind"] != "street")
    print(
        f"{OUTPUT.relative_to(ROOT)}: "
        f"교차로 {len(payload['intersections'])}개 · "
        f"링크 {len(payload['links'])}개(경계 {gates}) · "
        f"건물 {len(payload['buildings'])}개 · "
        f"{OUTPUT.stat().st_size:,} bytes"
    )


if __name__ == "__main__":
    main()
